MAILGUN_API_KEY: key-3m9dt4det38lfo-7z139upb1r1gzy044
MAILGUN_PUBLIC_API_KEY: pubkey-16vw-jrdj35mz1tcoz-ija45-ebxpqe2
MONGOLAB_URI: mongodb://launchbox_user:qwerty1234@ds027789.mongolab.com:27789/launchbox_gem_test
