development:
  sessions:
    default:
      uri: <%= ENV['MONGOLAB_URI'] %>
      options:
        max_retries: 1
        retry_interval: 0
production:
  sessions:
    default:
      uri: <%= ENV['MONGOLAB_URI'] %>
      options:
        max_retries: 1
        retry_interval: 0
